### ISSUE TITLE
Downloading and running in Visual Studio, out of the box

### ISSUE THREAD

**Issue by Neverfor** [halomademeapc/pokeR#47]
Hi there, 
I found your poker solution and it looks very good on the demo site. 
I tried running it locally, however, and it did not work out of the box. 

What I did: 
1) Downloaded ZIP file.
2) Unpacked and started the solution in Visual Studio 2019.
3) Restored all packaged, cleaned and rebuilt the solution.
4) Pressed Run button. 

What I receive, however is a message Cannot /GET, without any other explanation. 
I could search and try to debug it, but I thought I will ask you about it, since it should be working out of the box. 

I am working on a windows 2019 server. Core 3.1 and 5 SDK's are installed. NodeJs and Python 39 are installed. 
Below is the screenshot:

![image](https://user-images.githubusercontent.com/2330480/135237184-93ba5e48-6df8-4c86-9029-f3c64524a899.png)

P.S. As a side question, I am not really an Angular guy, but does your solution support SSL (https)?

**Comment by halomademeapc** [comment]
Hello, sounds like something prevented the angular app from compiling. Can you open a command linet at ClientApp and run ng build --prod to see if it gives you an error message?

The angular server is only used in development mode. In release the angular stuff is just a precompiled static resource that gets served up. HTTPS would be handled by kestrel or something else on your end. I personally use an nginx reverse proxy to handle all my https needs but you could also set the application up in IIS and handle it that way if you're tied to windows server

**Comment by Neverfor** [comment]
Thank you, for the fast response! 
So, I think I am missing something? (Not an Angular dev...)
![image](https://user-images.githubusercontent.com/2330480/135283875-55c1cf77-4bdd-4e42-97e4-d414d6cdd800.png)

I did install angular client, though. And I always thought that all ng files, could just be downloaded and restored from the packages... Am I wrong?

**Comment by halomademeapc** [comment]
It should usually take care of dependencies but if you're on an incompatible version of node.js it will throw a fuss. I will take a look at it when I get home from this trip in a few days

**Comment by Neverfor** [comment]
Alright, thanks for the tip! 
I will also try a few different versions of nodejs, to see if it will make it work.

**Comment by Neverfor** [comment]
Oh, just as a side-note: we tested PokeR, today, as a group of 9, and we noticed that people get disconnected (somtimes). 
Most of the time, we reconnect, very fast, but at times, we are missing, like half of the team. 
Container is running in an isolated Azure env, based on your docker container img.

**Comment by Neverfor** [comment]
Hi again,
I had very little time to check up on this, sorry. Tomorrow I will check it, again, but I tried node 14.

**Comment by Neverfor** [comment]
So, a few days turned into a week...
I reinstalled npm, and now I simply get an empty page:
![image](https://user-images.githubusercontent.com/2330480/141958371-3ad459a2-da11-44d7-a7c5-095dd5c094cb.png)

**Comment by Neverfor** [comment]
And tried it, again with node 12:
![image](https://user-images.githubusercontent.com/2330480/141961500-24fdb950-3b4c-41b3-9216-7a4f07599fca.png)


Same white page, after cleaning and rebuilding in the visual studio

**Comment by Neverfor** [comment]
This is the output from my Visual Stuido Code (I mostly use Visual Studio, but VS Code is not an issue):
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp> npm run build

> poker-web@2.0.0 build C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp
> ng build --prod

 10% building 3/4 modules 1 active ...-master\pokeR\ClientApp\src\styles.scssBrowserslist: caniuse-lite is outdated. Please run next command `npm update`

Date: 2021-11-16T09:44:03.879Z
Hash: c5b91c9a6d1fed4abaac
Time: 5061ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.01ecbc0fcff9207e8cde.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.a723c36635c3a098c2aa.js (polyfills) 130 bytes [initial] [rendered]
chunk {3}  (styles) [initial] [rendered]
chunk {scripts} scripts.0732a62b8691ce2d7b5a.js (scripts) 3.3 kB [entry] [rendered]

ERROR in ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\sass-loader\lib\loader.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\NormalModule.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\Compiler.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\webpack.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\architect\src\architect-legacy.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\architect\src\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\models\architect-command.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\commands\build-impl.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\models\command-runner.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\lib\init.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.sassLoader (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\sass-loader\lib\loader.js:46:72)
    at C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\NormalModule.js:301:20
    at C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:205:4
    at VirtualFileSystemDecorator.readFile (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:39:13)
    at processResource (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at iteratePitchingLoaders (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\loadLoader.js:47:3)
ERROR in Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\sass-loader\lib\loader.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\NormalModule.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\Compiler.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\webpack\lib\webpack.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\architect\src\architect-legacy.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\architect\src\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\models\architect-command.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\commands\build-impl.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\models\command-runner.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\lib\init.js
- C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.sassLoader (C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp\node_modules\sass-loader\lib\loader.js:46:72)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poker-web@2.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poker-web@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-11-16T09_44_03_973Z-debug.log
PS C:\Users\Administrator\Downloads\pokeR-master\pokeR-master\pokeR\ClientApp>

**Comment by Neverfor** [comment]
Just, a side question, do you run it on IIS server? (the thing you select, next to the play button in VS).

**Comment by Neverfor** [comment]
Alright, so, after playing for a while, I had to manually run the following commands:
npm install --save-dev node-sass

and finishing up with the whole npm install thingy:
![image](https://user-images.githubusercontent.com/2330480/141972633-439056de-f932-4ae7-9290-bb31d8584186.png)

Now, I have the solution running in the IIS server: 

![image](https://user-images.githubusercontent.com/2330480/141972748-bd14ae0d-30b7-4ed0-927f-37b238637a91.png)
