### ISSUE TITLE
Users who disconnect and immediately reconnect create duplicates for other clients

### ISSUE THREAD

**Issue by halomademeapc** [halomademeapc/pokeR#52]

**Comment by DingJianBEST** [comment]
@halomademeapc  Hi, do you have a plan to fix it

**Comment by halomademeapc** [comment]
I keep forgetting to, sorry. Had a lot going on in my life this past year and haven't had a lot of time for my dev projects

**Comment by halomademeapc** [comment]
#62 should fix this, need to do some manual testing since it's hard to simulate websocket disconnects
